const x = 10

try {
  console.log(x)
}catch(err){
    console.log(`erro: ${err}`)
}